# Generated by Django 5.0.4 on 2024-04-19 13:17

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_brand_image_alter_category_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('rate', models.IntegerField(default=1)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('True', 'True'), ('False', 'False')], default='New', max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '2. Comment',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('keywords', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=3)),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField()),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('featured_project', models.BooleanField(default=False)),
                ('Top_Deals_Of_The_Day', models.BooleanField(default=False)),
                ('Top_Selling_Products', models.BooleanField(default=False)),
                ('Recommended_For_You', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sub_category')),
                ('arm_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.arm_style')),
                ('assembly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.assembly')),
                ('back_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.back_style')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
                ('color', models.ManyToManyField(blank=True, to='product.color')),
                ('depth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.depth')),
                ('embellishment_feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.embellishment_feature')),
                ('fill_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.fill_material')),
                ('height', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.height')),
                ('height_base_to_top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.height_base_to_top')),
                ('included_components', models.ManyToManyField(blank=True, to='product.included_components')),
                ('item_depth_front_to_back', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.item_depth_front_to_back')),
                ('item_shape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.item_shape')),
                ('item_width_side_to_side', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.item_width_side_to_side')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.material')),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.pattern')),
                ('quality_certification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.quality_certification')),
                ('room_type', models.ManyToManyField(blank=True, to='product.room_type')),
                ('seat_back_interior_height', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.seat_back_interior_height')),
                ('seat_depth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.seat_depth')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.size')),
                ('special_features', models.ManyToManyField(blank=True, to='product.special_features')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.type')),
                ('upholstery_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.upholstery_color')),
                ('width', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.width')),
            ],
            options={
                'verbose_name_plural': '1. Product',
            },
        ),
        migrations.DeleteModel(
            name='Colour',
        ),
        migrations.AddField(
            model_name='images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
