# Generated by Django 5.0.4 on 2024-04-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_color_comment_images_product_delete_colour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
