# Generated by Django 5.0.4 on 2024-04-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_setting_icon_alter_setting_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='footer_color_1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='setting',
            name='footer_color_2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='setting',
            name='nav_color_1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='setting',
            name='nav_color_2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='setting',
            name='nav_color_3',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
