# Generated by Django 5.0.4 on 2024-04-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_banner_image_alter_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide_content',
            name='color',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image_2',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image_3',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image_4',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
